name: .NET Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Run tests
      run: dotnet test --no-build --configuration Release --collect:"XPlat Code Coverage" --results-directory ./coverage

    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage/**/coverage.cobertura.xml
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: false
        indicators: true
        output: both
        thresholds: '60 80'

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md

    # - name: Coverage Scope
    #   uses: DennisJensen95/coverage-scope@v0.5.1
    #   with:
    #     # The coverage file path to parse
    #     cfilename: coverage/**/coverage.cobertura.xml
    #     format: markdown
    #     # The branch to determine coverage for
    #     branch: main # default is main
    #     # The threshold to determine if coverage for the changed files is acceptable
    #     threshold-change: 80 # default is 80
    #     # The threshold to determine if total coverage is acceptable
    #     threshold-total: 90 # default is 80
