name: .NET Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Run tests
      run: dotnet test Demo-App.sln --no-build --configuration Release --collect:"XPlat Code Coverage;Format=json,lcov,cobertura" --results-directory ./coverage
    
    - name: Changed Files
      uses: lots0logs/gh-action-get-changed-files@2.1.4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Check test coverage
      uses: AveryCameronUofR/test-coverage-check-gh-action@1.0.10
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.base_ref }}
        minNewCoverage: 0.8 (Optional, 0.8 default)
        maxCoverageChange: 0.1 (Optional, 0.1 default)
    # - name: Coverage Scope
    #   if: always()
    #   uses: DennisJensen95/coverage-scope@v0.5.1
    #   id: codecoverage
    #   with:
    #     # The coverage file path to parse
    #     coverage-filepath: coverage/**/coverage.cobertura.xml
    #     # The branch to determine coverage for
    #     branch: main # default is main
    #     # The threshold to determine if coverage for the changed files is acceptable
    #     threshold-change: 100 # default is 80
    #     # The threshold to determine if total coverage is acceptable
    #     threshold-total: 50 # default is 80

    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage/**/coverage.cobertura.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'

    - name: ReportGenerator
      if: always()
      uses: danielpalme/ReportGenerator-GitHub-Action@5.4.5
      with:
        reports: coverage/**/coverage.cobertura.xml
        targetdir: 'coveragereport'
        toolpath: 'reportgeneratortool' # Default directory for installing the dotnet tool.
        reporttypes: 'HtmlInline;Cobertura;MarkdownSummary'

    - name: Upload coverage report artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: CoverageReport # Artifact name        
        path: coveragereport # Directory containing files to upload

    - name: Publish coverage in build summary # Testing to see
      if: always()
      run: cat coveragereport/Summary.md >> $GITHUB_STEP_SUMMARY # Adjust path and filename if necessary
      shell: bash
    
