name: .NET Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Run tests
      run: dotnet test --no-build --configuration Release --collect:"XPlat Code Coverage" --results-directory ./coverage

    - name: cobertura-report
      # You may pin to the exact commit or the version.
      # uses: 5monkeys/cobertura-action@ee5787cc56634acddedc51f21c7947985531e6eb
      uses: 5monkeys/cobertura-action@v14
      with:
        # The GITHUB_TOKEN for this repo
        # repo_token: # default is ${{ github.token }}
        # Path to the cobertura file.
        path: coverage/**/coverage.cobertura.xml # default is coverage.xml
        # If files with 100% should be skipped from report.
        skip_covered: false # default is true
        # Minimum allowed coverage percentage as an integer.
        minimum_coverage: 90
        # Fail the action when the minimum coverage was not met.
        fail_below_threshold: true # optional
        # Show line rate as specific column.
        # show_line: 
        # # Show branch rate as specific column.
        # show_branch: 
        # # Show class names instead of file names.
        # show_class_names: 
        # # Show line numbers of statements, per module, that was not executed.
        # show_missing: 
        # Crop missing line numbers strings that exceeds this length, provided as an integer.
        # show_missing_max_length: # optional, default is 
        # Link missing line numbers.
        link_missing_lines: true # optional
        # Source directory used for link_missing_lines.
        link_missing_lines_source_dir: true # optional, default is 
        # Only show coverage for changed files. (only if a PR is present)
        only_changed_files: true
        # Pull request number associated with the report. This property should be used when workflow trigger is different than pull_request.
        # pull_request_number: # optional, default is 
        # Use a unique name for the report and comment.
        #report_name: # optional, default is 
          
    # - name: Code Coverage Report
    #   uses: irongut/CodeCoverageSummary@v1.3.0
    #   with:
    #     # A comma separated list of code coverage files to analyse. Also supports using glob patterns to match multiple files.
    #     filename: coverage/**/coverage.cobertura.xml
    #     # Include a Line Rate coverage badge in the output using shields.io - true / false (default).
    #     badge: true # optional, default is false
    #     # Fail if overall Line Rate below lower threshold - true / false (default).
    #     fail_below_min: true # optional, default is false
    #     # Output Format - markdown or text (default).
    #     format: markdown # optional, default is text
    #     # Hide Branch Rate values in the output - true / false (default).
    #     hide_branch_rate: false # optional, default is false
    #     # Hide Complexity values in the output - true / false (default).
    #     hide_complexity: false # optional, default is false
    #     # Include health indicators in the output - true (default) / false.
    #     indicators: true # optional, default is true
    #     # Output Type - console (default), file or both.
    #     output: both # optional, default is console
    #     # Threshold percentages for badge and health indicators, lower threshold can also be used to fail the action.
    #     thresholds: '60 80' # optional, default is 50 75

    # - name: Add Coverage PR Comment
    #   uses: marocchino/sticky-pull-request-comment@v2
    #   if: github.event_name == 'pull_request'
    #   with:
    #     recreate: true
    #     path: code-coverage-results.md

    # - name: Coverage Scope
    #   uses: DennisJensen95/coverage-scope@v0.5.1
    #   with:
    #     # The coverage file path to parse
    #     coverage-filepath: coverage/**/coverage.cobertura.xml
    #     # The branch to determine coverage for
    #     branch: main # default is main
    #     # The threshold to determine if coverage for the changed files is acceptable
    #     threshold-change: 80 # default is 80
    #     # The threshold to determine if total coverage is acceptable
    #     threshold-total: 0 # default is 80
